// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: '${dotenv.env['Firebase_web_api_key']}',
    appId: '1:566049729985:web:df8197eee164b242ced340',
    messagingSenderId: '566049729985',
    projectId: 'custom-notification-sound-uber',
    authDomain: 'custom-notification-sound-uber.firebaseapp.com',
    storageBucket: 'custom-notification-sound-uber.firebasestorage.app',
    measurementId: 'G-5NVP5MJDMP',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: '${dotenv.env['Firebase_android_api_key']}',
    appId: '1:566049729985:android:7dda2f611a0c7a61ced340',
    messagingSenderId: '566049729985',
    projectId: 'custom-notification-sound-uber',
    storageBucket: 'custom-notification-sound-uber.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: '${dotenv.env['Firebase_ios_api_key']}',
    appId: '1:566049729985:ios:5cbcfd34ede6a602ced340',
    messagingSenderId: '566049729985',
    projectId: 'custom-notification-sound-uber',
    storageBucket: 'custom-notification-sound-uber.firebasestorage.app',
    iosBundleId: 'com.customnotification.sound.customNotificationSound',
  );
}
